# See https://pre-commit.com/ for usage and config
default_language_version:
  python: python3.7
default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: pipenv run isort
        language: python
        types: [python]

      - id: black
        name: black
        entry: pipenv run black
        language: python
        types: [python]

      - id: flake8
        name: flake8
        entry: pipenv run flake8
        language: python
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        entry: pipenv run mypy
        language: python
        types: [python]
        pass_filenames: false
        exclude: auth.py

      - id: pytest
        name: pytest
        entry: pipenv run pytest test
        language: python
        types: [python]

      - id: pytest-cov
        name: pytest
        stages: [push]
        entry: pipenv run pytest test/ --cov --cov-fail-under=70
        language: python
        types: [python]
        pass_filenames: false
